#added a rule to compile ASCIIArt using the g++ compiler
compile:
	g++ ASCIIArt.cpp
#added a rule to build the program using the g++ compiler

build:
	g++ -o ASCIIArt.exe *.o
#added a rule to delete .exe (a.out) files

clean:
	rm -f *.exe *.o
#added a rule to run the program

run: 
	./ASCIIArt